name: CI
on: [push, pull_request]

jobs:
  build_test:
    name: Build and Test
    strategy:
      matrix:
        go: ['1.18.x', '1.19.x', '1.20.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-go@v2.1.5
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - uses: actions/cache@v2.1.7
      with:
        path: ~/go/pkg/mod
        key: ubuntu-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ubuntu-go-
    - name: Test
      run: go test -race ./...
    - name: Test Verbose
      run: go test -race -v ./...
